### ISSUE TITLE
Weird error message for object copy a file from staging

### ISSUE THREAD

**Issue by joereuss12** [PelicanPlatform/pelican#101]
When testing out pelican client with my own director running as well as my own generated token, I get a panic error when running pelican object copy for the first time (accessing the file from the origin rather than the cache). This error only appears when grabbing from the origin and not when accessed from the cache. The error is below:

```DEBUG[2023-09-05T15:23:59Z] Starting the HTTP transfer...                

panic: increment required before ewma iteration update

goroutine 87 [running]:
github.com/vbauerster/mpb/v7.(*Bar).DecoratorEwmaUpdate.func1(0xc000de5e68?)
        /go/pkg/mod/github.com/vbauerster/mpb/v7@v7.5.3/bar.go:266 +0xb8
github.com/vbauerster/mpb/v7.(*Bar).serve(0xc000198ea0, {0x1a82828, 0xc000512d70}, 0xc0007fc5a0)
        /go/pkg/mod/github.com/vbauerster/mpb/v7@v7.5.3/bar.go:349 +0xfc
created by github.com/vbauerster/mpb/v7.newBar
        /go/pkg/mod/github.com/vbauerster/mpb/v7@v7.5.3/bar.go:84 +0x1c5
```
Seems to be some error with progress bars. The file does download **successfully** so this bug is not fatal but looks like it is because of the panic. Should be fixed

**Comment by bbockelm** [comment]
Looks like a bug in the underlying library -- is there a newer version available?

**Comment by joereuss12** [comment]
Yes, looks like the library is on v8 now instead of v7. I can try to make some changes to see if it'll fix it.
