### ISSUE TITLE
`object share` crashes when given a URL without a path component following the namespace prefix

### ISSUE THREAD

**Issue by brianaydemir** [PelicanPlatform/pelican#1697]
Pelican Version:
```
Version: 7.10.11
Build Date: 2024-10-23T17:58:48Z
Build Commit: 5f47b175fe62f8f650ab4696a2cb90fcd351436c
Built By: goreleaser
```

Pelican Service:
- [x] Client

**Describe the bug**
`object share` crashes when given a URL without a path component following the namespace prefix.

For example (note the lack of a trailing `/` on the URL):

```[baydemir@local ~]> rm -rf ~/.config/pelican/
[baydemir@local ~]> pelican object share osdf://ospool/ap40/data
The client is able to save the authorization in a local file.
This prevents the need to reinitialize the authorization for each transfer.
You will be asked for this password whenever a new session is started.
Please provide a new password to encrypt the local OSDF client configuration file: 

panic: runtime error: slice bounds out of range [17:12]

goroutine 1 [running]:
github.com/pelicanplatform/pelican/oauth2.AcquireToken({0xc000b385d0, 0x1a}, 0xc0005eedc0, {{0xc0005fb320, 0x6, 0x6}, 0x0, {{0xc0008b8088, 0x1, 0x1}}, ...}, ...)
	/home/runner/work/pelican/pelican/oauth2/oauth2.go:86 +0xad0
github.com/pelicanplatform/pelican/client.AcquireToken(0xc0008cc240, {{0xc0005fb320, 0x6, 0x6}, 0x0, {{0xc0008b8088, 0x1, 0x1}}, {{0xc000afff1a, 0x11}, ...}, ...}, ...)
	/home/runner/work/pelican/pelican/client/acquire_token.go:283 +0x1085
github.com/pelicanplatform/pelican/client.CreateSharingUrl({0x3070f78, 0xc000a3def0}, 0xc0008cc240, 0x0)
	/home/runner/work/pelican/pelican/client/sharing_url.go:106 +0x37c
main.shareMain(0x3dacc20, {0xc000a14f20, 0x1, 0x25cacb8?})
	/home/runner/work/pelican/pelican/cmd/object_share.go:68 +0x154
github.com/spf13/cobra.(*Command).execute(0x3dacc20, {0xc000a14ee0, 0x1, 0x1})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x87c
github.com/spf13/cobra.(*Command).ExecuteC(0x3dafd00)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:985
main.Execute()
	/home/runner/work/pelican/pelican/cmd/root.go:89 +0x8f
main.handleCLI({0xc00003e080, 0x4, 0x4})
	/home/runner/work/pelican/pelican/cmd/main.go:66 +0x1cc
main.main()
	/home/runner/work/pelican/pelican/cmd/main.go:35 +0x28
```

**To Reproduce**
1. Remove `~/.config/pelican/`.
2. Run `pelican object share osdf://ospool/ap40/data`.

**Expected behavior**
A descriptive error message instead of a stack trace. Alternatively, assume a trailing `/`.

**Desktop (please complete the following information):**
 - OS: macOS

**Additional context**
The lack of a trailing slash looks less obviously wrong when the namespace prefix itself contains no slashes, as in `osdf://nsdf`.

**Comment by brianaydemir** [comment]
Still an issue in:
```
Version: 7.12.0-rc.3
Build Date: 2025-01-06T16:27:35Z
Build Commit: 41b624a616cf84bb57956f272fda5bc54ce63205
Built By: goreleaser
```

**Comment by brianaydemir** [comment]
The crash is occurring in: https://github.com/PelicanPlatform/pelican/blob/5f9d427c9c4bb8b48c784718600a533bae9ef6a5/oauth2/oauth2.go#L83-L93

**Comment by bbockelm** [comment]
@brianaydemir - you assigned this to yourself.  Are you planning to work on it or should I move the assignment to someone else?
