### ISSUE TITLE
Panic on download of file to `/dev/null`

### ISSUE THREAD

**Issue by jhiemstrawisc** [PelicanPlatform/pelican#368]
I ran `pelican object copy /gluex/uconn1/rawdata/test/testFileSize1GB /dev/null` and the first time it worked fine.

The second time I ran the command, I got this error:

```
EBUG[2023-11-10T15:45:58Z] Parsed Cache: http://stash-cache-shoveler.osgdev.chtc.io:8000/gluex/uconn1/rawdata/test/testFileSize1GB 
DEBUG[2023-11-10T15:45:58Z] Transfers:                                   
DEBUG[2023-11-10T15:45:58Z] Constructed URL: http://stash-cache.osg.chtc.io:8000/gluex/uconn1/rawdata/test/testFileSize1GB 
DEBUG[2023-11-10T15:45:58Z] Transfer URL String: http://stash-cache.osg.chtc.io:8000/gluex/uconn1/rawdata/test/testFileSize1GB 
DEBUG[2023-11-10T15:45:58Z] Starting the HTTP transfer...                
null 0.00 b / 0.00 b [-----------------------------------------------------------------------------------------------------------------------------------------------------------------] 0s ] 0.00 b/s
null 976.56 MiB / 976.56 MiB [=================================================================================================================================================================] Done!
DEBUG[2023-11-10T15:45:58Z] Got error from file transfer                 
DEBUG[2023-11-10T15:45:58Z] Failed to download: transfer error: Unable to read /gluex/uconn1/rawdata/test/testFileSize1GB; permission denied 
DEBUG[2023-11-10T15:45:58Z] Constructed URL: http://sc-cache.chtc.wisc.edu:8000/gluex/uconn1/rawdata/test/testFileSize1GB 
DEBUG[2023-11-10T15:45:58Z] Transfer URL String: http://sc-cache.chtc.wisc.edu:8000/gluex/uconn1/rawdata/test/testFileSize1GB 
DEBUG[2023-11-10T15:45:58Z] Starting the HTTP transfer...                
panic: *mpb.Progress instance can't be reused after it's done

goroutine 119 [running]:
github.com/vbauerster/mpb/v8.(*Progress).MustAdd(...)
        /root/go/pkg/mod/github.com/vbauerster/mpb/v8@v8.6.1/progress.go:141
github.com/vbauerster/mpb/v8.(*Progress).New(0x10e12a0?, 0x1c264?, {0xffff9805e440?, 0x40009f8370?}, {0x4000ac4a70, 0x2, 0x2})
        /root/go/pkg/mod/github.com/vbauerster/mpb/v8@v8.6.1/progress.go:131 +0x84
github.com/vbauerster/mpb/v8.(*Progress).AddBar(0x40002adc20?, 0x17c4e48?, {0x4000ac4a70, 0x2, 0x2})
        /root/go/pkg/mod/github.com/vbauerster/mpb/v8@v8.6.1/progress.go:121 +0x124
github.com/pelicanplatform/pelican/client.DownloadHTTP({{{0x111ff2b, 0x4}, {0x0, 0x0}, 0x0, {0x400093c388, 0x1b}, {0xffffdb1b991d, 0x2a}, {0x0, ...}, ...}, ...}, ...)
        /workspaces/pelican/pelican/client/handle_http.go:515 +0x1f7c
github.com/pelicanplatform/pelican/client.startDownloadWorker({0xffffdb1b991d, 0x2a}, {0xffffdb1b9948, 0x9}, {0x0, 0x0}, {0x40002eca00, 0x3, 0x0?}, 0x0?, ...)
        /workspaces/pelican/pelican/client/handle_http.go:382 +0x2e0
created by github.com/pelicanplatform/pelican/client.download_http
        /workspaces/pelican/pelican/client/handle_http.go:332 +0x894
```

**Comment by jhiemstrawisc** [comment]
After a very quick skim of the code, I think this is caused by the fact that the first cache we try returns a `permission denied` error, and when we try to download from the second cache, we end up using an already initialized and completed progress bar object.
